version: '3.4'

services:
  app:
    ports:
      - 80:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/web/
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./app:/var/www/html/app/
      - ./bin:/var/www/html/bin/
      - ./var:/var/www/html/var/
      - ./src:/var/www/html/src/
      - ./web:/var/www/html/web/
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./.gitignore:/var/www/html/.gitignore
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SalesTaxes
      MYSQL_USER: dev_usr
      MYSQL_PASSWORD: dev_passwd
    ports:
      - 6033:3306