<?php

namespace AppBundle\Repository;

/**
 * ShoppingBasketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingBasketsRepository extends \Doctrine\ORM\EntityRepository
{
}
